# Generated by Django 4.0.3 on 2022-06-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('createdby', models.CharField(max_length=200)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
