# Generated by Django 4.0.4 on 2022-06-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0002_alter_usersignup_interestedtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fb', models.URLField()),
                ('twitter', models.URLField()),
                ('date', models.DateTimeField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.usersignup')),
            ],
        ),
    ]
