# Generated by Django 4.0.4 on 2022-06-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0003_authordetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='isAuthor',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
