# Generated by Django 4.0.4 on 2022-06-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('slug', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('file', models.CharField(max_length=500, null=True)),
                ('views', models.IntegerField(default=0, null=True)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('article', models.TextField()),
                ('createdby', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
